TEMPLATE	= lib
LANGUAGE	= C++

CONFIG	+= plugin

HEADERS	+= Decoder.h

SOURCES	+= Decoder.cpp

LIBS += -L/usr/lib

######################################################################
# Automatically generated by qmake (1.07a) Tue Aug 31 19:40:49 2010
######################################################################




# Input
