INSERT INTO Transaction_Type(tr_type, name) VALUES(11, 'Регистрация');
INSERT INTO Transaction_Type(tr_type, name) VALUES(12, 'Сторно');
INSERT INTO Transaction_Type(tr_type, name) VALUES(14, 'Налог');
INSERT INTO Transaction_Type(tr_type, name) VALUES(15, 'Скидка суммой на позицию');
INSERT INTO Transaction_Type(tr_type, name) VALUES(16, 'Надбавка суммой на позицию');
INSERT INTO Transaction_Type(tr_type, name) VALUES(17, 'Скидка процентная на позицию');
INSERT INTO Transaction_Type(tr_type, name) VALUES(18, 'Надбавка процентная на позицию');
INSERT INTO Transaction_Type(tr_type, name) VALUES(35, 'Скидка суммой на чек');
INSERT INTO Transaction_Type(tr_type, name) VALUES(36, 'Надбавка суммой на чек');
INSERT INTO Transaction_Type(tr_type, name) VALUES(37, 'Скидка процентная  на чек');
INSERT INTO Transaction_Type(tr_type, name) VALUES(38, 'Надбавка процентная на чек');
INSERT INTO Transaction_Type(tr_type, name) VALUES(40, 'Оплата с вводом суммы клиента');
INSERT INTO Transaction_Type(tr_type, name) VALUES(41, 'Оплата без ввода суммы клиента');
INSERT INTO Transaction_Type(tr_type, name) VALUES(50, 'Внесение');
INSERT INTO Transaction_Type(tr_type, name) VALUES(51, 'Выплата');
INSERT INTO Transaction_Type(tr_type, name) VALUES(55, 'Закрытие чека');
INSERT INTO Transaction_Type(tr_type, name) VALUES(56, 'Отмена чека');
INSERT INTO Transaction_Type(tr_type, name) VALUES(57, 'Чек отложен');
INSERT INTO Transaction_Type(tr_type, name) VALUES(58, 'Отложенный чек восстановлен');
INSERT INTO Transaction_Type(tr_type, name) VALUES(60, 'Отчет без гашения');
INSERT INTO Transaction_Type(tr_type, name) VALUES(61, 'Закрытие смены');
INSERT INTO Transaction_Type(tr_type, name) VALUES(62, 'Открытие смены');
INSERT INTO Transaction_Type(tr_type, name) VALUES(63, 'Отчет с гашением');