#!/bin/bash
if ! gksu --message "Введите пароль администратора" "/usr/bin/dnc_Transaction_export" ; then
zenity --warning --text "Введите правильный пароль администратора" ;
fi
/usr/bin/pcmanfm /dnc_arch