######################################################################
# Automatically generated by qmake (1.07a) Mon Feb 14 14:36:04 2011
######################################################################

TEMPLATE = lib
LANGUAGE = C+

CONFIG	+= plugin

INCLUDEPATH += . ../../../bin/include

LIBS	+= -L/usr/lib/

# Input
HEADERS += printform.ui.h
INTERFACES += printform.ui

unix {
  UI_DIR = .ui
  MOC_DIR = .moc
  OBJECTS_DIR = .obj
}

TARGET = dncprintformlib
