TEMPLATE	= lib
LANGUAGE	= C++

CONFIG	+= plugin

LIBS	+= -L/usr/lib -L/usr/lib/pgsql -lpq -L../../../bin/lib -lhwsrv -ldncdllog -ldncreceipt -ldncsetupparam -ldncaddonfunc -ldncwaresystem -ldncutil

INCLUDEPATH	+= /usr/include/pgsql ../../../bin/include

HEADERS	+= kkmregistration.h

SOURCES	+= kkmregistration.cpp

TARGET = dnckkmregistration


unix {
  UI_DIR = .ui
  MOC_DIR = .moc
  OBJECTS_DIR = .obj
}



######################################################################
# Automatically generated by qmake (1.07a) Tue May 19 15:25:52 2009
######################################################################


# Input
